# GitHub Pages Configuration
# This file is used by GitHub Pages to configure the site

# Site settings
title: "TropoMetrics - Leiden Weather Dashboard"
description: "Real-time weather data for Leiden, Netherlands using Open-Meteo API"
baseurl: ""
url: "https://TomTheLEGEND23.github.io"

# GitHub Pages settings
github:
  repository_name: "HHS-TropoMetrics"
  repository_url: "https://github.com/TomTheLEGEND23/HHS-TropoMetrics"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Include files that start with underscores
include:
  - _site

# Plugins (if needed in the future)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO and meta tags
lang: en
author: "HHS TropoMetrics Team"
google_analytics: # Add your GA tracking ID here if needed

# Social media and sharing
twitter:
  username: # Add Twitter handle if applicable
  card: summary

# Additional metadata
repository: "TomTheLEGEND23/HHS-TropoMetrics"
