apiVersion: apps/v1
kind: Deployment
metadata:
  name: tropometrics-deployment
  labels:
    app: tropometrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tropometrics
  template:
    metadata:
      labels:
        app: tropometrics
    spec:
      containers:
      - name: tropometrics
        image: ghcr.io/tomthelegend23/hhs-tropometrics:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tropometrics-service
  labels:
    app: tropometrics
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: tropometrics
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tropometrics-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tropometrics.local  # Change this to your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tropometrics-service
            port:
              number: 80